/* empty css                      */import{a as u,S as m,i as f}from"./assets/vendor-frHSA4Lh.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))a(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const s of o.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&a(s)}).observe(document,{childList:!0,subtree:!0});function i(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function a(t){if(t.ep)return;t.ep=!0;const o=i(t);fetch(t.href,o)}})();function p(e){return u.defaults.baseURL="https://pixabay.com/api/",u.get("",{params:{key:"50295834-c918df4fa87d72bde5e1e5104",q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:9}}).then(function(r){if(r.status!==200)throw new Error(`HTTP error! status: ${r.status}`);return r.data}).catch(function(r){console.log(r)}).finally(function(){})}const d=document.querySelector(".gallery");let y=new m(".gallery a",{captionsData:"alt",captionDelay:250});function h(e){return e&&e.charAt(0).toUpperCase()+e.slice(1).toLowerCase()}function g(e){const r=e.map(i=>{const t=["likes","views","comments","downloads"].map(o=>`<p class="info-item">${h(o)}:<span class="info">${i[o]}</span></p>`).join("");return`<li class="image-item">
    <a href="${i.largeImageURL}" title="${i.tags}">
    <img src="${i.webformatURL}" 
    alt="${i.tags}"
    />
    </a>
    <div class="gallery-info">
    ${t}
    </div>
    </li>`}).join("");d.insertAdjacentHTML("beforeend",r),y.refresh()}function L(){d.innerHTML=""}function b(){const e=document.querySelector(".loader");e&&(e.style.display="inline-block")}function l(){const e=document.querySelector(".loader");e&&(e.style.display="none")}const S=document.querySelector(".form"),n=document.querySelector('input[name="search-text"]'),c=document.querySelector('button[type="submit"]');c.disabled=n.value.trim()==="";n.addEventListener("input",()=>{c.disabled=n.value.trim()===""});S.addEventListener("submit",e=>{e.preventDefault();const r=n.value.trim();if(r===""){c.disabled=!0;return}L(),b(),p(r).then(i=>{l(),i.hits&&i.hits.length>0?g(i.hits):f.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"})}).catch(i=>{f.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}),console.error(i),l()})});l();
//# sourceMappingURL=index.js.map
